require: rubocop-rspec

AllCops:
  Include:
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*.rb'
    - 'bin/**/*'
    - 'spec/**/*.rb'
    - 'lib/**/*.rake'

Rails:
  Enabled: true
  DisplayCopNames: true
  RunRailsCops: true
  StyleGuideCopsOnly: false

Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*.rb'
    - 'config/**/*.rb'
Metrics/MethodLength:
  Max: 20
  Enabled: false
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 15
  Enabled: false
  Exclude:
    - 'spec/**/*.rb'

Style/Documentation:
  Include:
    - 'app/**/*.rb'
  Exclude:
    - 'app/controllers/**/*.rb'
    - 'app/decorators/**/*.rb'
    - 'app/helpers/**/*.rb'
    - 'app/mailers/**/*.rb'
    - 'app/policies/**/*.rb'
    - 'app/serializers/**/*.rb'
    - 'app/views/**/*.rb'
    - 'spec/**/*.rb'

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/**/*.rb'
    - 'app/decorators/**/*.rb'
    - 'app/serializers/**/*.rb'
    - 'app/policies/**/*.rb'

Style/BarePercentLiterals:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*'

Style/MultilineTernaryOperator:
  Enabled: false

Style/BlockEndNewline:
  Exclude:
    - 'spec/**/*'

Style/PredicateName:
  Exclude:
    - 'app/decorators/**/*.rb'

Style/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*.rb'

Style/WordArray:
  Exclude:
    - 'spec/**/*.rb'

Style/Semicolon:
  Exclude:
    - 'spec/**/*.rb'

Style/Proc:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

RSpec/InstanceVariable:
  Exclude:
    - 'spec/shared_contexts/**/*.rb'

RSpec/FilePath:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false