development: &my_settings
  enable_star: true
  min_prefix_len: 0
  min_infix_len: 1
  min_word_len: 1
  charset_type: utf-8
  morphology: stem_en, stem_ru
test:
  <<: *my_settings
  mysql41: 9307
production:
  <<: *my_settings
  pid_file: ~home/deployer/qna/shared/tmp/pids/searchd.pid
  indices_location: ~home/deployer/qna/shared/db/sphinx
  configuration_file: ~home/deployer/qna/shared/config/production.sphinx.conf
  binlog_path: ~home/deployer/qna/shared/binlog
